pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                sh "pip install -r requirements.txt"
            }
        }
        stage("Unit Test") {
            steps {
                sh "rm -rf test-reports"
                sh "python3 test_point_manager.py"
            }
            post {
                always {
                    junit "test-reports/*.xml"
                }
            }
        }
        stage("Integration Test") {
            steps {
                sh "rm -rf api-test-reports"
                sh "python3 test_points_api.py"
            }
            post {
                always {
                    junit "api-test-reports/*.xml"
                }
            }
        }
    }
}
